### ISSUE TITLE
Movimento CIRCULAR

### ISSUE THREAD

**Issue by MLK3** [poli-libras/virtual-jonah#4]
Adicionar suporte ao movimento circular

**Comment by leonardofl** [comment]
Feito \o/ (ao longo de vários commits na branch transition).

* https://github.com/poli-libras/virtual-jonah/blob/master/src/br/usp/libras/jonah/HandGraph.java
* https://github.com/poli-libras/virtual-jonah/blob/master/src/br/usp/libras/jonah/interpolation/CircularInterpolation.java
